/*
 * app/index.js
 * Cross platform entry point for your app.
 * Here, we configure the redux store, register all the screens, and start the app with a navigation stack.
 * -----
 * Generated by dfrn
 */

import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
import { Provider } from 'react-redux';
import { createStore } from 'redux';

import configureStore from 'app/config/store';

import MainStack from 'app/routers/MainStack';

class Root extends Component {

	constructor(props) {
		super(props);
		this.store = configureStore();
	}

	render() {
		return (
			<Provider store={this.store}>
				<MainStack />
			</Provider>
		);
	}
}

AppRegistry.registerComponent('RNDF', () => Root);

export default Root;